<Project>

    <PropertyGroup>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    <PropertyGroup>
        <AnalysisLevel>latest-All</AnalysisLevel>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <TrimmerSingleWarn>false</TrimmerSingleWarn>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)'=='Release'">
        <DebugSymbols>False</DebugSymbols>
        <DebugType>None</DebugType>
        <PublishDocumentationFiles>false</PublishDocumentationFiles>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="GitVersion.MsBuild" Version="6.1.0" />
        <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556" />
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="$(SolutionDir)stylecop.json" />
    </ItemGroup>

    <!-- TODO get rid of this - proper native libraries! -->
    <PropertyGroup>
        <TargetPlatform Condition="$([MSBuild]::IsOsPlatform('Windows'))">win-x64</TargetPlatform>
        <TargetPlatform Condition="$([MSBuild]::IsOsPlatform('Linux'))">linux-x64</TargetPlatform>
        <TargetPlatform Condition="$([MSBuild]::IsOsPlatform('OSX'))">osx-x64</TargetPlatform>
    </PropertyGroup>

</Project>
