<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks> <!-- TODO remove -->
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\OpenRA.Mods.Common\OpenRA.Mods.Common.csproj"/>
	</ItemGroup>

</Project>
